---
#-------------------------------
# General Site Settings

titulo: 36 Encuentro Plurinacional <br>de Mujeres y Disidencias 

logo:
author: 36encuentropluri
description: Pagina del 36 encuentro plurinaciones de mujeres y disidencias
email: 36encuentropluri.info@gmail.com
#phone: +880 2544 658 256
#address:  USA
#copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: Que es, link: "/quees" }
  - { name: Actividades, link: "/actividades" }
  - { name: Logistica, link: "/logistica" }
  - { name: Contacto, link: "/contacto" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Main Section

main:
  main-titulo: 36° Encuentro Plurinacional de Mujeres, Lesbianas, Travestis, Trans, Bisexuales, Intersexuales </br> y No Binaries
  main-subtitulo: 14, 15 y 16 de  octubre 2023 - Bariloche / Furilofche
  main-button-texto: ¿Qué es?
  main-button-url: "/quees"
  main-button-texto-2: Ver Cronograma de Actividades
  main-button-url-2: "/quees"

  social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-instagram", link: "#" }
  
#-------------------------------
# Porque (Section and Page)
porque-titulo: ¿Por qué acá?
porque-contenido: La indignación colectiva del movimiento de mujeres y disidencias frente al violento desalojo de la comunidad Lafken Winkul Mapu en el cual fueron detenidas por causas excarcelables, mujeres mapuche junto a sus niñes, impulsó la elección de Bariloche como sede.<br><br>Esta situación y la de todas las mujeres indígenas en conflicto territorial será parte de la agenda de los feminismos durante los tres días del Encuentro.
porque-button-texto: Leer más
button-url: "/porque"

#-------------------------------
# Talleres y Actividades (Section and Page)
actividades:
  actividades-titulo: Debatimos nuestras prácticas
  actividades-contenido: Debatimos nuestras prácticas <br>  El corazón de los encuentros son los talleres. Históricamente estos se conforman por las y les participantes del Encuentro, son democráticos, horizontales y pluralistas. Están organizados por ejes temáticos en los cuales se discute, comparte experiencias y se llega a consensos y conclusiones que quedan a disposición para cualquiera y como insumo para los siguientes Encuentros. 
  actividades-button-texto: Conoce los talleres
  actividades-button-url: "/talleres"

#-------------------------------
# Logistica (Section and Page)
logistica:
  logistica-titulo: Alojamiento, Transporte e Información útil
logistica-sections:
  - {
      titulo: Alojamiento,
      icon: ti-home,
      descripcion: "Conocé diversas opciones de alojamiento",
      button-texto: Ver más,
      button-url: ,
    }
  - {
      titulo: Transporte,
      icon: ti-car,
      descripcion: "Medios de transporte disponibles en la ciudad",
      button-texto: Ver más,
      button-url: ,
    }
  - {
      titulo: Mapa,
      icon: ti-map-alt,
      descripcion: "Hospitales, baños y lugares de ocio, entre otros",
      button-texto: Ver más,
      button-url: ,
    }


#-------------------------------
# Varios Section

varios: 
varios-sections:
  - {
      titulo: Inscripciones,
      icon: ti-check-box,
      descripcion: "<br> 
      La inscripción no es obligatoria. Podés participar de todo sin restricciones. Sin embargo, tu aportes económico sirve para garantizar la realización de este encuentro.<br>",
      button-url: /actividades,
      button-texto: "Formulario",
      activo: ,# Add true to select section
    }
  - {
      titulo: Aportes,
      icon: ti-money,
      descripcion: "Los encuentros son autónomos. <br> No se aceptan contribuciones que impliquen condicionamientos. La construcción la hacemos entre todas y todes, si querés aportar podes hacerlo directamente a la cuenta de la comisión organizadora.",
      button-url: /actividades,
      button-texto: "Ver más",
      activo: , # Add true to select section
    }
  
#-------------------------------
# Contact Section

contact-title: Informacion de contacto
contact-email: 36encuentropluri.info@gmail.com


# Work Process Section
quees-pilares:
quees-pilares-titulo: "Su éxito y crecimiento se basa en  ocho pilares que los caracterizan:" 

quees-pilares-sections:
  - titulo: "Autoconvocados"
    icon: "assets/images/icons/plan.png"
    contenido: "Cada año, en el lugar elegido como sede,  se auto convocan todas y todes las y les  que lo deseen para conformar la  Comisión Organizadora, desde donde  participan a título individual. La comisión organizadora se ocupa de organizar el  encuentro y las decisiones se toman por consenso."

  - titulo: "Autónomos y autofinanciados"
    icon: "assets/images/icons/plan.png"
    contenido: "La decisión de crear un espacio  independiente va de la mano de no  aceptar ninguna contribución económica  que implique condicionamientos. Nadie  por fuera de la comisión organizadora  puede influir y direccionar los Encuentros."

  - titulo: "Plurales"
    icon: "assets/images/icons/plan.png"
    contenido: "Implica la multiplicación de participantes  que garantizan la abierta conformación  de las comisiones organizadoras en cada  lugar y a su vez la amplia participación  sin restricciones de las mujeres y  disidencias."

  - titulo: "Plurinacionales"
    icon: "assets/images/icons/plan.png"
    contenido: "En los encuentros participamos  identidades de distintos orígenes étnico  raciales, migrantes y de los pueblos  originarios."
  
  - titulo: "Democráticos y horizontales"
    icon: "assets/images/icons/plan.png"
    contenido: "Todas y todes pueden hacer oír su voz.  No existen estructuras jerárquicas ni  referentes. Ninguna tiene la palabra por  encima de las otras. Los Encuentros no  emiten resoluciones, sino conclusiones  propias de cada taller de debate y no del  conjunto del encuentro."

  - titulo: "Federales"
    icon: "assets/images/icons/plan.png"
    contenido: "Se abren a su realización en todas las  provincias del interior del país. Amplía no  sólo la cantidad, sino también la calidad  de la participación de las mujeres y  disidencias a lo largo y ancho del  territorio nacional."
